export const data = [
  {
    id: 1,
    title: "Colorado",
    desc: "Rocky Mountain National Park is a natural wonder that is a must-see attraction for anyone visiting Colorado. The park spans over 415 square miles and boasts over 300 miles of hiking trails that wind through alpine meadows, crystal-clear lakes, and cascading waterfalls. Visitors can spot an array of wildlife such as elk, moose, bighorn sheep, and black bears while enjoying the scenic vistas of towering peaks and glacier-carved valleys. The Rockies are formed of a complex network of mountain ranges that were created over millions of years by tectonic activity and volcanic eruptions. The rocks in the Rockies range from ancient sedimentary rocks, such as limestone and sandstone, to volcanic rocks, such as basalt and andesite. The range is divided into several distinct regions, each with its own unique geology. The climate in the Rocky Mountains varies depending on the altitude and location. The higher elevations are generally colder and experience more precipitation, while the lower elevations are warmer and drier. Snow is common in the winter months, and the region is known for its skiing and winter sports. In the summer, the weather is generally mild, with warm temperatures and occasional thunderstorms. The Rocky Mountains are a popular destination for outdoor enthusiasts, and the region attracts millions of visitors each year. Activities in the region include hiking, camping, fishing, hunting, skiing, snowboarding, and rock climbing. The area is also rich in mineral resources, such as gold, silver, copper, and coal, and mining has been an important industry in the region for centuries.",
    image:
      "https://cdn.pixabay.com/photo/2016/09/19/13/37/colorado-1680301_960_720.jpg",
  },
  {
    id: 2,
    title: "Philippines",
    desc: "The island country, the Philippines, is one of the most beautiful countries where blue and green are together. Forget the potion of youth, traveling to the Philippines will rejuvenate you for at least 5 years. The Philippines is located in the western Pacific Ocean, and is surrounded by several other countries, including China, Taiwan, and Indonesia. The country covers an area of over 300,000 square kilometers, and is divided into three main island groups: Luzon, Visayas, and Mindanao. The Philippines has a unique culture that is influenced by its history of Spanish and American colonization, as well as its indigenous traditions. The country is known for its vibrant festivals, including the Sinulog Festival in Cebu, the Ati-Atihan Festival in Aklan, and the MassKara Festival in Bacolod. The Philippines is also famous for its music, which includes traditional forms such as kundiman and harana, as well as modern pop and rock music. The Philippines is a popular tourist destination, known for its stunning beaches, tropical climate, and friendly people. Some of the most popular tourist destinations include Boracay Island, Palawan Island, and the Chocolate Hills in Bohol. The country also has several UNESCO World Heritage Sites, including the historic city of Vigan and the Tubbataha Reef Natural Park.",
    image:
      "https://bigseventravel.com/wp-content/uploads/2019/11/john-hernandez-IL-fBBnF-GU-unsplash-1920x1440.jpg",
  },
  {
    id: 3,
    title: "Bali",
    desc: "Bali, Indonesia's most famous island, has taken its place as the 'last paradise' in mind. Providing 80% of its livelihood with tourism, Bali hosts thousands of tourists every year. Bali is located in the westernmost end of the Lesser Sunda Islands, between Java to the west and Lombok to the east. The island covers an area of about 5,780 square kilometers and is home to a population of over 4 million people. Bali has a unique culture that is heavily influenced by Hinduism. The island is known for its colorful ceremonies and festivals, such as the Nyepi Day of Silence and the Galungan Festival. Balinese culture is also expressed through dance, music, and art, with traditional forms such as gamelan music and wayang shadow puppetry being popular throughout the island. Bali is one of the most popular tourist destinations in Southeast Asia, attracting millions of visitors each year. The island is famous for its stunning beaches, which offer opportunities for swimming, surfing, and sunbathing. Other popular tourist attractions include the rice terraces in Ubud, the cliffside Uluwatu Temple, and the sacred Monkey Forest Sanctuary in Ubud. Bali is famous for its arts and crafts, with traditional forms such as woodcarving, painting, and batik being popular throughout the island. Bali is also known for its silver jewelry, which is crafted by local artisans using traditional techniques.",
    image: "https://images.pexels.com/photos/3772406/pexels-photo-3772406.jpeg",
  },
  {
    id: 4,
    title: "Wyoming",
    desc: "Yellowstone National Park is a vast protected area located primarily in the U.S. state of Wyoming, although it also extends into Montana and Idaho. Established in 1872, it was the first national park in the United States and is widely considered to be the first national park in the world. Yellowstone is known for its natural beauty and unique geologic features, such as the famous Old Faithful geyser and the colorful Grand Prismatic Spring. Wyoming is the 10th largest state in the US, covering an area of over 97,000 square miles. It is bordered by Montana to the north, South Dakota and Nebraska to the east, Colorado to the south, and Utah and Idaho to the west. The state is home to a diverse range of landscapes, including the Rocky Mountains, high plains, forests, and deserts. Wyoming is home to some of the most iconic national parks and monuments in the US, including Yellowstone National Park, Grand Teton National Park, and Devils Tower National Monument. These areas are famous for their stunning landscapes, wildlife, and geological features. Wyoming is home to a diverse range of wildlife, including bison, elk, moose, bighorn sheep, pronghorn antelope, and grizzly bears. The state is also a popular destination for birdwatchers, as it is home to numerous species of birds, including golden eagles, bald eagles, and great horned owls. Wyoming has a rich history, with evidence of human habitation dating back over 12,000 years. The state was home to several Native American tribes, including the Shoshone, Arapaho, and Crow. In the late 1800s, Wyoming became known for its role in the expansion of the American West, with the establishment of several important trails, such as the Oregon Trail and the Pony Express. Wyoming is a popular destination for outdoor enthusiasts, with a wide range of recreational activities available throughout the state. Some popular activities include hiking, camping, fishing, hunting, skiing, snowmobiling, and rock climbing. The state is also home to several popular ski resorts, such as Jackson Hole and Grand Targhee.",
    image:
      "https://images.pexels.com/photos/2416600/pexels-photo-2416600.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 5,
    title: "Cappadocia",
    desc: "Cappadocia… 'Kappa Tuchia', which means 'Land of Beautiful Horses' in the words of Persians. A location in Turkey and in the center of Anatolia's most popular and unique tourist centers of someone who Cappadocia, magnificent nature, valleys of unique beauty, fairy chimneys, rock-hewn settlements, millions every year with open-air museums and underground cities, local and hosts foreign tourists. Cappadocia has a rich history that dates back thousands of years. The region was inhabited by several civilizations, including the Hittites, Persians, Greeks, Romans, and Byzantines. The early Christian communities also lived in Cappadocia and carved their churches and monasteries into the soft rock formations. During the 4th century, Cappadocia became an important center of early Christianity, and many of the famous Cappadocian Fathers, including St. Basil the Great, St. Gregory of Nyssa, and St. Gregory Nazianzen, lived and preached in the region. Cappadocia is known for its unique geological formations, which were formed by volcanic activity and erosion over millions of years. The region is characterized by its distinctive fairy chimneys, which are tall, cone-shaped rock formations with a mushroom-like cap. The soft tuff rock in the region was eroded by wind and water, creating caves and valleys that were used by the early inhabitants for shelter and protection. Cappadocia is home to many cultural sites, including the Goreme Open-Air Museum, which features rock-cut churches and frescoes dating back to the 10th century. Other notable sites include the Derinkuyu Underground City, which was used by early Christians to escape persecution, and the Kaymakli Underground City, which is one of the largest underground cities in Cappadocia. Cappadocia is a popular tourist destination and offers a range of activities for visitors. Tourists can take hot-air balloon rides over the fairy chimneys, hike through the valleys, explore the underground cities, and visit the numerous cave dwellings and rock-cut churches. The region is also famous for its pottery and carpets, and visitors can learn about these traditional crafts by visiting local workshops. Overall, Cappadocia is a fascinating region with a rich history and unique geological formations. Its cultural sites, underground cities, and cave dwellings make it a popular destination for tourists from around the world.",
    image:
      "https://images.pexels.com/photos/2325447/pexels-photo-2325447.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 6,
    title: "Switzerland",
    desc: "The Swiss Alps are one of the most iconic mountain ranges in the world, located in the central region of Switzerland. The Swiss Alps are renowned for their spectacular peaks, glacial valleys, crystal-clear lakes, and stunning landscapes. They offer some of the best skiing and snowboarding in Europe, as well as a range of outdoor activities like hiking, mountain biking, and paragliding. The Swiss Alps are renowned for their stunning natural beauty, including snow-capped peaks, crystal-clear lakes, and picturesque villages. The region is home to several famous landmarks, such as the Matterhorn, Eiger, and Jungfrau mountains, as well as the Aletsch Glacier, the largest glacier in the Alps. The Swiss Alps are a popular tourist destination, attracting millions of visitors each year. The region offers a wide range of outdoor activities, including skiing, snowboarding, hiking, and mountain biking. Some popular destinations include St. Moritz, Zermatt, and Interlaken, as well as smaller, picturesque villages such as Grindelwald and Murren. The Swiss Alps are home to several distinct cultures, including the Romansh-speaking Graubünden region, as well as German, French, and Italian-speaking regions. The region is also known for its traditional alpine architecture, with many villages featuring wooden chalets and barns.",
    image:
      "https://images.pexels.com/photos/267104/pexels-photo-267104.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 7,
    title: "Antalya",
    desc: "Antalya is a city located on the Mediterranean coast of Turkey and is home to some of the most beautiful beaches in the world. Antalya beach, in particular, is one of the most popular and scenic spots in the region. With its crystal-clear turquoise waters, fine golden sand, and stunning mountain views. Antalya has a wide range of attractions and activities that cater to all interests. Some of the popular places to visit in Antalya include the historic old town, the ancient Roman ruins of Perge and Aspendos, the stunning Düden Waterfalls, and the Antalya Museum, which displays a wide range of artifacts from the region's history. For those who enjoy outdoor activities, Antalya offers opportunities for hiking in the nearby mountains, rafting on the rivers, and sunbathing on the beautiful beaches. There are also numerous water sports activities available, such as jet skiing, parasailing, and scuba diving. Antalya has a wide range of accommodation options, from luxury resorts to budget hotels and guesthouses. Many of the hotels are located on or near the beach, offering stunning views of the Mediterranean Sea. The city center also has a variety of hotels, including boutique hotels and hostels.",
    image:
      "https://images.pexels.com/photos/8633909/pexels-photo-8633909.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 8,
    title: "Sinop",
    desc: "Sinop Hamsilos is a natural wonder located on the Black Sea coast of Turkey, near the city of Sinop. Hamsilos is a narrow and winding canyon that stretches for about 2.5 kilometers, flanked by steep and towering cliffs that rise up to 100 meters high. The canyon opens up into a beautiful and secluded bay, where the crystal-clear waters of the Black Sea lap gently against the pebbly shore. The area around Sinop Hamsilos is also home to a variety of plant and animal species, including rare orchids and endemic fish. The region has been designated as a protected area to preserve its ecological and cultural significance. In addition to its natural beauty, Sinop Hamsilos is also a popular destination for tourists seeking outdoor activities such as hiking, swimming, and fishing. There are several hiking trails in the area that offer stunning views of the harbor and surrounding landscape. Overall, Sinop Hamsilos is a must-visit destination for those interested in natural beauty and outdoor recreation in Turkey.",
    image:
      "https://cdn.pixabay.com/photo/2017/09/01/16/54/landscape-2704821_960_720.jpg",
  },
  {
    id: 9,
    title: "Northern Lights",
    desc: "Northern lights, the 'Aurora Borealis', named after the Dawn Goddess Aurora, are the natural glows that emerge in the sky with the interaction of the earth's magnetic field and charged particles from the Sun. This image, which makes most of us feel like in a fairy tale land, deserves to be visited at least once in a lifetime. The Northern Lights can be seen in several countries, including Norway, Sweden, Finland, Iceland, Canada, and Russia. They are most visible during the winter months, from late September to early April, when the nights are long and dark. The colors of the Northern Lights can vary from green to pink, red, purple, and blue. The colors depend on the altitude of the charged particles and the type of gas particles in the Earth's atmosphere that they interact with. To see the Northern Lights, it is best to be in a location with little light pollution, such as a remote area or a designated viewing site. It is also recommended to check the aurora forecast before heading out to increase the chances of seeing the lights.",
    image:
      "https://images.unsplash.com/photo-1579033461380-adb47c3eb938?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MXx8bm9ydGhlcm4lMjBsaWdodHN8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&w=1000&q=80",
  },
  {
    id: 10,
    title: "Fuji Mountain",
    desc: "The symbol and highest mountain of Japan, Mount Fuji is considered sacred by the Japanese and is called Fuji-San. This mountain, which has an active startovolcano, is depicted in art and photography and is a natural wonder visited by athletes and tourists. Mount Fuji is located on the border of Yamanashi and Shizuoka prefectures and is visible from Tokyo on a clear day. The mountain has been a symbol of Japanese culture and identity for centuries, and it has been depicted in numerous paintings, photographs, and literary works. Climbing Mount Fuji is a popular activity among tourists and locals alike. The climbing season typically runs from early July to mid-September, and there are several trails leading to the summit. The most popular trail is the Yoshida Trail, which starts from the fifth station and takes about 5-7 hours to reach the summit. In addition to hiking, there are several other activities to enjoy in the Mount Fuji area, including hot springs, museums, and scenic drives. The area also offers stunning views of the surrounding landscape, including Lake Kawaguchi and the Hakone area.",
    image:
      "https://d20aeo683mqd6t.cloudfront.net/articles/title_images/000/038/943/original/pixta_43064884_S.jpg?2019&d=750x400",
  },
  {
    id: 11,
    title: "Arashiyama Bamboo Grove",
    desc: "Bamboo Forest, or Arashiyama Bamboo Grove or Sagano Bamboo Forest, is a natural forest of bamboo in Arashiyama, Kyoto, Japan. The forest consists mostly of Moso Bamboo (Phyllostachys edulis) and consists of several pathways for tourists and visitors. The Ministry of the Environment considers it a part of the soundscape of Japan. The bamboo grove covers an area of about 16 square kilometers and is considered one of the most beautiful and peaceful natural sights in Kyoto. The bamboo stalks can grow up to 30 meters high, and the sound of the leaves rustling in the wind creates a soothing sound that adds to the overall ambiance of the grove. The Arashiyama Bamboo Grove is also home to several temples and shrines, including Tenryuji Temple, which is a UNESCO World Heritage Site. Visitors can enjoy a leisurely stroll through the bamboo grove, take photos, and explore the nearby attractions. The best time to visit the Arashiyama Bamboo Grove is during the early morning or late afternoon when the sunlight filtering through the bamboo creates a stunning visual effect. The grove can be crowded during peak tourist season, so it is recommended to visit during weekdays or off-peak periods.",
    image: "https://wallpaperaccess.com/full/534182.jpg",
  },
  {
    id: 12,
    title: "Antelope Canyon",
    desc: "Antelope Canyon is a slot canyon in the American Southwest, on Navajo land east of Page, Arizona. It includes two separate, scenic slot canyon sections, referred to as Upper Antelope Canyon (or The Crack), and Lower Antelope Canyon (or The Corkscrew). There are two sections of Antelope Canyon: Upper Antelope Canyon and Lower Antelope Canyon. Both canyons are accessible by guided tours only, as they are located on Navajo Nation land. The guided tours offer visitors the opportunity to explore the canyon and learn about its geology and cultural significance. Upper Antelope Canyon is the more popular of the two canyons and is known for its iconic light beams that filter down from the top of the canyon, creating a surreal and otherworldly atmosphere. The best time to see the light beams is during midday, when the sunlight is strongest. Lower Antelope Canyon is narrower and requires more physical activity to navigate. It is known for its unique rock formations and vivid colors, created by the sunlight filtering through the canyon walls.",
    image:
      "https://images.pexels.com/photos/13572581/pexels-photo-13572581.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
];
